baseURL = "https://yagune.de"
title = "yagune.de"
theme = "schwarz"

pygmentscodefences = true
pygmentsoptions = "linenos=true"

enableGitInfo = true
rssLimit = 20
paginate = 20

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

PluralizeListTitles = false

[markup]
  defaultMarkdownHandler = "goldmark"

[frontmatter]
  date = ["publishDate", "date", "lastmod"]
  lastmod = [":git", "lastmod", "date", "publishDate"]

[permalinks]
  blog = "/:sections/:year/:month/:title/"

[Params]
  giturl = "https://github.com/YuriGassner/Blog_Stuff"
  dateFormat = "2006-01-02"
  showCC = true
  showBY = true
  showSA = true
  sectionsToSortAlphabetically = ["recipes"]

[[languages.de.menu.main]]
  name = "Home"
  url = "/de/"
  weight = 1
[[languages.en.menu.main]]
  name = "Home"
  url = "/en/"
  weight = 1

[[languages.de.menu.main]]
  name = "Blog"
  url = "/de/blog/"
  weight = 2
[[languages.en.menu.main]]
  name = "Blog"
  url = "/en/blog/"
  weight = 2

[[languages.de.menu.main]]
  name = "Rezepte"
  url = "/de/recipes/"
  weight = 3
[[languages.en.menu.main]]
  name = "Recipes"
  url = "/en/recipes/"
  weight = 3

[[languages.de.menu.main]]
  name = "Impressum"
  url = "/de/impressum/"
  weight = 4
[[languages.en.menu.main]]
  name = "Imprint"
  url = "/en/imprint/"
  weight = 4

[languages]
  [languages.de]
    languageName = "Deutsch"
    contentDir = "content/de"
    languageCode = "de-DE"
      [languages.de.params]
        copyrightPage = "copyright.md"
  [languages.en]
    languageName = "English"
    contentDir = "content/en"
    languageCode = "en-US"
      [languages.en.params]
        copyrightPage = "copyright.md"
